{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "hazelcast-cluster.fullname" . }}-discovery
  labels:
    {{- include "hazelcast-cluster.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "endpoints", "services"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hazelcast-cluster.fullname" . }}-discovery
  labels:
    {{- include "hazelcast-cluster.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "hazelcast-cluster.fullname" . }}-discovery
subjects:
  - kind: ServiceAccount
    name: {{ include "hazelcast-cluster.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
