apiVersion: v1
kind: Service
metadata:
  name: {{ include "hazelcast-cluster.fullname" . }}
  labels:
    {{- include "hazelcast-cluster.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: hazelcast
      port: {{ .Values.service.port }}
      targetPort: hazelcast
      protocol: TCP
  selector:
    {{- include "hazelcast-cluster.selectorLabels" . | nindent 4 }}
